apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-fsii
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-fsii
    app.kubernetes.io/part-of: burrs-node-app
  name: node-express-hello-fsii
  namespace: bgriggs-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: node-express-hello-fsii
    weight: null
status: {}
